version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27018
    volumes:
      - mongodb_data_container:/d/Developer/Interview/Angel_one/data
volumes:
  mongodb_data_container: