version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27018
    volumes:
      - mongodb_data_container:/d/Developer/Interview/Angel_one/data
    networks:
      - app-network
  angelone:
    build: .
    command: npm run dev
    env_file: .env
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network
volumes:
  mongodb_data_container:
networks:
  app-network:
    driver: bridge